spring:
#H2
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    password: sa
#  h2:
#    console:
#      enabled: 'true'
#      path: /h2-console
#  jpa:
#    open-in-view: 'false'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: 'true'
#    show-sql: 'true'
#    hibernate:
#      ddl-auto: 'update'

#SUPABASE
#  datasource:
#    url: jdbc:postgresql://db.niocqzxypzutwctzuyfj.supabase.co:5432/postgres?user=postgres&password=c8-11-m-javaangular
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

#GOOGLECLOUD
  datasource:
    username: dsformo
    url: jdbc:mysql://35.224.79.221:3306/portfolio-mrb
    password: test123456

#LOCAL
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/dbcharta
#    password: 43824382
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
        ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8081

# Api-Fixer KEY:
api.key.fixer:
api.url.fixer:
api.header-field.fixer:

# Api-SendGrid KEY:
api.key.sendgrid:
api.template.welcome.id:
app.email:
